production:
  adapter: mysql2
  encoding: utf8
  pool: 30
  username: <%= ENV['DB_USERNAME'] %>
  password:  <%= ENV['DB_PASSWORD'] %>
  database_url: <%= ENV['DB_URL'] %>
  port: <%= ENV['DB_PORT'] %>
  database: <%= ENV['DB_NAME'] %>

development:
  adapter: mysql2
  encoding: utf8
  pool: 30
  username: <%= ENV['DB_USERNAME'] %>
  password:  <%= ENV['DB_PASSWORD'] %>
  database_url: <%= ENV['DB_URL'] %>
  port: <%= ENV['DB_PORT'] %>
  database: <%= ENV['DB_NAME'] %>
  